# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: xhblog
subtitle: '现代化个人博客'
description: '分享技术、设计与生活'
keywords: '前端, 设计, 技术'
author: Xiao He
language: zh-CN
timezone: 'Asia/Shanghai'

# URL 【线上正常专用】
url: https://hezhanleiok.github.io/hexo/
root: /hexo/
relative_link: true
permalink: :year/:month/:day/:slug/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
meta_generator: true

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'mtime'

# Pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
include:
exclude:
ignore:

# Extensions
theme: butterfly

# Deployment
deploy:
  type: git
  repo: https://github.com/hezhanleiok/hexo.git
  branch: gh-pages

# Dashboard
dashboard:
  admin: $2b$12$1a1nju3MxACdmBeVtcm.D.xqjl822sCBdN4JUXqvV/q2OOhcEXAKq
  secret: your-secret-key
  port: 4000
